### ISSUE TITLE
Compile failure with earmark 1.4.41

### ISSUE THREAD

**Issue by nathany-copia** [phenixdigital/phoenix_storybook#347]
phoenix_storybook 0.5.6 fails to compile after upgrading to earmark 1.4.41

```
== Compilation error in file lib/phoenix_storybook/guides/guides.ex ==
** (UndefinedFunctionError) function :string_lexer.string/1 is undefined (module :string_lexer is not available)
    :string_lexer.string(~c"Basic component documentation is in `PhoenixStorybook.Story`.")
    (earmark 1.4.41) lib/earmark_parser/helpers/leex_helpers.ex:20: EarmarkParser.Helpers.LeexHelpers.tokenize/2
    (earmark 1.4.41) lib/earmark_parser/helpers/lookahead_helpers.ex:17: EarmarkParser.Helpers.LookaheadHelpers.opens_inline_code/1
    (earmark 1.4.41) lib/earmark_parser/parser.ex:658: EarmarkParser.Parser._inline_or_text?/2
    (earmark 1.4.41) lib/earmark_parser/parser.ex:486: EarmarkParser.Parser._consolidate_para/4
    (earmark 1.4.41) lib/earmark_parser/parser.ex:215: EarmarkParser.Parser._parse/4
    (earmark 1.4.41) lib/earmark_parser/parser.ex:68: EarmarkParser.Parser.lines_to_blocks/3
    (earmark 1.4.41) lib/earmark_parser/parser.ex:60: EarmarkParser.Parser.parse_lines/3
could not compile dependency :phoenix_storybook, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phoenix_storybook --force", update it with "mix deps.update phoenix_storybook" or clean it with "mix deps.clean phoenix_storybook"
```

Current work around is to lock earmark on 1.4.40 (the suggestions to update/clean/etc. didn't resolve the issue)

https://github.com/pragdave/earmark

**Comment by cblavier** [comment]
I'm not sure I get the issue, I just opened a new branch (see #348) with the latest earmark `1.4.43` and I got no issue whatsoever.
WDYT?

**Comment by nathany-copia** [comment]
Thank you. It looks like it was a problem with earmark 1.4.42 specifically. They should probably yank that version.
https://github.com/pragdave/earmark/blob/master/RELEASE.md

https://github.com/pragdave/earmark/issues/468

**Comment by cblavier** [comment]
Got it, thanks!
